FROM maven:3.5.3-jdk-8-alpine AS MAVEN_BUILD
MAINTAINER Swann
COPY pom.xml /build/
WORKDIR /build/
RUN mvn dependency:go-offline
COPY src /build/src/
RUN mvn -Dmaven.test.skip  package
ARG SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ARG SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ARG SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ARG SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
ENV SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
ARG SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
ENV SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
ARG SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
ENV SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
ARG SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
ENV SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/synergieFamily-0.0.1-SNAPSHOT.jar /app/
EXPOSE 8080
ENTRYPOINT ["java", "-jar","-Dspring.profiles.active=prod", "wildCircus-0.0.1-SNAPSHOT.jar"]